export const AUTHOR = 'NARUMI NOGAWA'
export const TITLE = 'FRONTEND DEVELOPER'
export const MAIL = 'narutyan0711@gmail.com'
export const URL_GITHUB = 'https://github.com/naruwo-github'
export const URL_HATENA = 'https://chan-naru.hatenablog.com/'
export const URL_QIITA = 'https://qiita.com/chan_naruwo'
export const URL_INSTAGRAM = 'https://www.instagram.com/chan_naru_way/'